[package]
name = "bookbinding-tools"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "make-galley"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
pdfium-render = {version= "0.8.35", features = ["static"]}
