[package]
name = "bookbinding-tools"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "make-galley"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
lopdf = "0.36.0"
